/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module 'sst' {
  export interface Resource {
    Backend: {
      type: 'sst.aws.ApiGatewayV2'
      url: string
    }
    ImovelOshiroClient: {
      id: string
      secret: string
      type: 'sst.aws.CognitoUserPoolClient'
    }
    ImovelOshiroUserPool: {
      id: string
      type: 'sst.aws.CognitoUserPool'
    }
    MyApi: {
      name: string
      type: 'sst.aws.Function'
      url: string
    }
    OshiroImovelBucket: {
      name: string
      type: 'sst.aws.Bucket'
    }
    bucket: {
      name: string
      type: 'sst.aws.Bucket'
    }
    table: {
      name: string
      type: 'sst.aws.Dynamo'
    }
    web: {
      type: 'sst.aws.Nextjs'
      url: string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import 'sst'
export {}
